In [7]:
#課題1
list = [1,2,3,4,5,6,7,8,9,10]
print(list)

#課題2
evens = list[1::2]
print(evens)

#課題3
alphabets = ["a","b","c","d","e","f"]
dict = {}
for i,n in enumerate(alphabets):
    dict.update({i:n})
    
print(dict)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[2, 4, 6, 8, 10]
{0: 'a', 1: 'b', 2: 'c', 3: 'd', 4: 'e', 5: 'f'}


In [14]:
#課題4
class Human:
    counter = 0
    def __init__(self, name, age, sex, height, weight):
        self.n = name
        self.a = age
        self.s = sex
        self.h = height
        self.w = weight
        Human.counter += 1
        
    def increment(self):
        self.a += 1
        
y = Human("山田",23,"男",170.3,60.2)
t = Human("高橋",30,"女",165.2,46.2)

y.increment()
print(y.a)

print(Human.counter)

24
2


In [15]:
#課題5
import numpy as np

A = np.array([[1,2],[2,3],[3,4]])
B = np.array([[1,2,3],[4,5,6]])
print(np.dot(A,B))

[[ 9 12 15]
 [14 19 24]
 [19 26 33]]


In [18]:
#課題6
import numpy as np

A = np.array([1,2,3])
B = np.array([-1,9,6])

a = np.linalg.norm(A)
b = np.linalg.norm(B)
c = np.dot(A,B)

print("cos = {}".format(c/(a*b)))

cos = 0.861118704783965
