In [14]:
#課題１

li = list(range(1,11))
li

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [15]:
#課題２
#1~10の偶数のみのリスト作成
en = list(range(2,11,2))
en

[2, 4, 6, 8, 10]

In [16]:
#課題３
#リストから辞書型に変換する
def list_to_dic(key_list, val_list):
    return dict(zip(key_list, val_list))
    
lis = ["a","b","c","d","e","f"]
nl = list(range(0,6))

list_to_dic(nl,lis) 



{0: 'a', 1: 'b', 2: 'c', 3: 'd', 4: 'e', 5: 'f'}

In [17]:
#課題３
#Humanクラスの作成
class Human:
    
    count = 0
   
   
    
 
    
    def __init__(self, name, age, sex, height, weight):
        self.name = name
        self.age = age
        self.sex = sex
        self.height = height
        self.weight = weight
        Human.count += 1
        
    def age_plus(self,age):
         self.age += 1
    
    @classmethod
    def count_instance(self):
        return self.count
        
         

        
        
a =Human("山田", 23,  "男性",170.3 ,60.2)
b = Human("高橋", 23,  "女性",165.2 ,46.2)

a.age_plus(a.age)


print(" %s, %d歳.sex: %s.Height: %dcm.Weight: %dkg." % (a.name, a.age,a.sex,a.height,a.weight))
print(Human.count_instance())

 山田, 24歳.sex: 男性.Height: 170cm.Weight: 60kg.
2


In [18]:
#課題5
import numpy as np
x = np.arange(9).reshape((3, 3))
y =np.arange(6).reshape((3, 2))

In [19]:
np.dot(x,y)

array([[10, 13],
       [28, 40],
       [46, 67]])

In [20]:
#課題6
x = np.arange(3)
data = [1,4,5,7]
y = np.array(data)

In [21]:
np.cos(x)


array([ 1.        ,  0.54030231, -0.41614684])

In [22]:
np.cos(y)

array([ 0.54030231, -0.65364362,  0.28366219,  0.75390225])